#!/bin/bash

regex1="changed: (.*)"
regex2="changed: (.*)\."

monitor-sensor | while read -r line; do
	if [[ $line =~ $regex1 ]]; then
		case ${BASH_REMATCH[1]} in
			"left-up")
				if [ $(cat ~/.config/i3/rotatelock) -eq 0 ]; then
					flip left
					fi
				;;
			"right-up")
				if [ $(cat ~/.config/i3/rotatelock) -eq 0 ]; then
					flip right
				fi
				;;
			"bottom-up")
				if [ $(cat ~/.config/i3/rotatelock) -eq 0 ]; then
					flip up
					fi
				;;
			"normal")
				if [ $(cat ~/.config/i3/rotatelock) -eq 0 ]; then
					flip down
					fi
				;;
			*)
				if [ $(cat ~/.config/i3/brightnesslock) -eq 0 ]; then
					[[ $line =~ $regex2 ]]
					xbacklight -set $((${BASH_REMATCH[1]} / 10 + 20)) -steps 500
					fi
				;;
		esac
	fi
done
