#!/bin/bash
case $1 in
up)
	xinput set-prop "SYNA2B29:00 06CB:77C6" "Device Enabled" 0
	pkill compton
	xrandr --output eDP-1 --rotate inverted
	compton -CGb --backend glx --vsync opengl
	/home/eero/.fehbg
	xinput set-prop "ELAN21EF:00 04F3:227C" "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
	;;
down)
	xinput set-prop "SYNA2B29:00 06CB:77C6" "Device Enabled" 1
	pkill compton
	xrandr --output eDP-1 --rotate normal
	compton -CGb --backend glx --vsync opengl
	/home/eero/.fehbg
	xinput set-prop "ELAN21EF:00 04F3:227C" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
	;;
left)
	xinput set-prop "SYNA2B29:00 06CB:77C6" "Device Enabled" 0
	pkill compton
	xrandr --output eDP-1 --rotate left
	compton -CGb --backend glx --vsync opengl
	/home/eero/.fehbg
	xinput set-prop "ELAN21EF:00 04F3:227C" "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
	;;
right)
	xinput set-prop "SYNA2B29:00 06CB:77C6" "Device Enabled" 0
	pkill compton
	xrandr --output eDP-1 --rotate right
	compton -CGb --backend glx --vsync opengl
	/home/eero/.fehbg
	xinput set-prop "ELAN21EF:00 04F3:227C" "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1
	;;
esac
