#!/bin/bash
case $1 in
up)
	xinput set-prop 10 "Device Enabled" 0
	xrandr --output eDP-1 --rotate inverted
	xinput set-prop 11 136 -1 0 1 0 -1 1 0 0 1
	;;
down)
	xinput set-prop 10 "Device Enabled" 1
	xrandr --output eDP-1 --rotate normal
	xinput set-prop 11 136 1 0 0 0 1 0 0 0 1
	;;
left)
	xinput set-prop 10 "Device Enabled" 0
	xrandr --output eDP-1 --rotate left
	xinput set-prop 11 136 0 -1 1 1 0 0 0 0 1
	;;
right)
	xinput set-prop 10 "Device Enabled" 0
	xrandr --output eDP-1 --rotate right
	xinput set-prop 11 136 0 1 0 -1 0 1 0 0 1
	;;
esac
