#!/bin/bash
if [ "$(pidof i3)" != "" ]; then
	IN=/tmp/lockinpipe.png
	OUT=/tmp/lockoutpipe.png
	mkfifo $IN
	mkfifo $OUT
	scrot $IN &
	convert $IN -blur 0x5 $OUT &
	i3lock -ue -p default -i $OUT
	rm $IN
	rm $OUT
fi
